CREATE TABLE new_leaves_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fullname TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);



ALTER TABLE new_leaves_articles
  ADD COLUMN
    author INTEGER REFERENCES new_leaves_users(id)
    ON DELETE SET NULL;
